name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ make

    - name: Build the project
      run: |
        g++ -Wall -g -o calculator calculator.cpp

    - name: Run tests (if any)
      run: |
        # Add your test commands here if you have tests
        ./calculator

    - name: Clean up
      run: |
        rm calculator
